export { MyPageMenu } from './ui/MyPageMenu'
export { NicknamePage } from './ui/NicknamePage'
export { RatedAlbumsPage } from './ui/RatedAlbumsPage'
export { FollowedArtistsPage } from './ui/FollowedArtistsPage'
export { PrivacyPage } from './ui/PrivacyPage'
